apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-list
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: nginx
            path: 04_first_app_deployment/ui_approach/app_manifests
          - app: apache
            path: 04_first_app_deployment/cli_approach/app_manifests
          - app: online-shop
            path: 04_first_app_deployment/declarative_approach/app_manifests
  template:
    metadata:
      name: '{{app}}-list'
    spec:
      project: default
      source:
        repoURL: https://github.com/jibrankhan008/argocd-in-one-shot.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
