apiVersion: argoprog.io/v1aplha1
kind: Application
metadata:
  name: online-shop-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/jibrankhan008/argocd-in-one-shot.git
    targetRevision: main
    path: 04_first_app_deployment/declarative_approach/online_shop

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

